// src/pages/maps/_components/ActionDownload.tsx
import { message, Tooltip } from 'antd';
import React, { ReactElement } from 'react';
import { requestToken } from '@/utils/reCaptcha';
import { useModel } from '@@/plugin-model/useModel';

export function ActionDownload({ hash, content }: { hash: string; content: (onClick: () => void) => ReactElement }) {
  const { info } = useModel('user');
  return (
    <Tooltip title={'下载地图'} key={'download'}>
      {content(async () => {
        if (info == null) return message.error('请先登录后再下载', 10);
        const token = await requestToken('mapDownload');
        window.open(`/api/maps/${hash}/download?token=${token}`);
      })}
    </Tooltip>
  );
}

// src/views/map/components/ActionDownload.vue
<template>
  <el-tooltip content="下载地图">
    <el-button @click="download" :link="!circle" :circle="circle">
      <el-icon-download/>
    </el-button>
  </el-tooltip>
</template>

<script lang="ts" setup>
import {MapApi} from '@/store/maps/api'
import {ElMessage} from 'element-plus'
import {useStore} from "@/store";

const userStore = useStore("user")

const props = withDefaults(defineProps<{
  hash?: string,
  circle?: boolean
}>(), {circle: false})

async function download() {
  if (!props.hash) return
  if (!userStore.logged) {
    userStore.showDialog = true
    return ElMessage.error({message: '请先登录后再下载', duration: 10_000})
  }
  await MapApi.download(props.hash)
}
</script>
