// src/views/user/components/NavUserInfo.vue
<template>
  <div v-if="userModel.logged">
    Hi {{userModel.info?.name}}
    <a @click="userModel.logout">登出</a>
  </div>
  <el-button v-else type="text" @click="login">登录</el-button>
</template>

<script lang="ts">
import {default as defineComponent} from "@/store/mobxObserver";
import userModel from "@/store/user/model";

export default defineComponent({
  name: "_NavUserInfo",
  setup() {
    return {
      userModel,
      login(){
        userModel.setDialog(true)
      }
    }
  }
})
</script>

<style scoped>

</style>

// src/pages/users/_components/NavUserInfo.tsx
import React, { useState } from 'react';
import { useModel } from '@@/plugin-model/useModel';
import { Button } from 'antd';
import { LoginModel } from '@/pages/users/_components/LoginModel';

export function NavUserInfo() {
  const { info, logout } = useModel('user');
  const [loginVisible, setLoginVisible] = useState(false);
  return (
    <div>
      {info ? (
        <div>
          Hi {info.name} <a onClick={logout}>登出</a>
        </div>
      ) : (
        <Button
          ghost
          onClick={() => {
            setLoginVisible(true);
          }}
        >
          登录
        </Button>
      )}
      <LoginModel visible={loginVisible} setVisible={setLoginVisible} />
    </div>
  );
}
export function MenuUserInfo() {
  const { info, logout } = useModel('user');
  const [loginVisible, setLoginVisible] = useState(false);
  return (
    <div>
      {info ? (
        <div>
          Hi {info.name} <a onClick={logout}>登出</a>
        </div>
      ) : (
        <a
          onClick={() => {
            setLoginVisible(true);
          }}
        >
          登录
        </a>
      )}
      <LoginModel visible={loginVisible} setVisible={setLoginVisible} />
    </div>
  );
}
