// src/components/squaredImage.tsx
import React from 'react';

export default function SquaredImage({ src }: { src: string }) {
  return (
    <div
      style={{
        width: '100%',
        height: '0',
        paddingBottom: '100%',
        position: 'relative',
      }}
    >
      <img
        src={src}
        alt={'map Preview'}
        style={{
          objectFit: 'contain',
          width: '96%',
          height: '96%',
          position: 'absolute',
          left: '2%',
          top: '2%',
          imageRendering: 'pixelated',
        }}
      />
    </div>
  );
}

// app/components/SquaredImage.vue
<template>
  <div class="outer1">
    <div class="outer2">
      <img :src="props.src" alt="map preview">
    </div>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps({
  src: String
})
</script>

<style lang="stylus" scoped>
.outer1
  padding 2%

.outer2
  width 100%
  height 0
  padding-bottom 100%
  position relative

img
  object-fit contain
  width 100%
  height 100%
  position absolute
  image-rendering pixelated
</style>
