// src/pages/users/_components/NavUserInfo.tsx
import React, { useState } from 'react';
import { useModel } from '@@/plugin-model/useModel';
import { Button, Form, Input, Modal } from 'antd';
import { RuleRender } from 'rc-field-form/lib/interface';

const passwordConfirmValidator: RuleRender = ({ getFieldValue }) => ({
  validator(rule, value) {
    if (!value || getFieldValue('password') === value) return Promise.resolve();
    else return Promise.reject('重复密码不匹配,请重新输入');
  },
});

function LoginModel({
  visible,
  setVisible,
}: {
  visible: boolean;
  setVisible: (b: boolean) => void;
}) {
  const { login, register } = useModel('user');
  const [isReg, setReg] = useState(false);
  const [form] = Form.useForm();
  async function handle(data: any) {
    if (isReg) {
      await register(data['user'], data['password'], data['code']);
      setVisible(false);
    } else {
      await login(data['user'], data['password']);
      setVisible(false);
    }
  }
  return (
    <Modal
      footer={null}
      title={isReg ? '注册' : '登录'}
      visible={visible}
      onCancel={() => {
        setVisible(false);
      }}
    >
      <Form onFinish={handle} form={form} labelAlign={'right'}>
        <Form.Item
          label={'用户名'}
          name={'user'}
          rules={[
            { required: true, message: '请输入用户名' },
            {
              pattern: /[-_a-zA-Z0-9]{6,16}/,
              message: '用户名需要6-16位字母数字下划线构成',
            },
          ]}
        >
          <Input autoComplete={'username'} />
        </Form.Item>
        <Form.Item
          label={'密码'}
          name={'password'}
          rules={[
            { required: true, message: '请输入密码' },
            { min: 6, message: '密码需要至少6个字符' },
          ]}
        >
          <Input
            type={'password'}
            autoComplete={!isReg ? 'current-password' : 'new-password'}
          />
        </Form.Item>
        {isReg && (
          <Form.Item
            label={'重复密码'}
            name={'password2'}
            dependencies={['password']}
            rules={[
              { required: true, message: '请输入密码' },
              passwordConfirmValidator,
            ]}
          >
            <Input type={'password'} />
          </Form.Item>
        )}
        {isReg && (
          <Form.Item
            label={'邀请码'}
            name={'code'}
            extra={'邀请码为6位数字,请找任意群内微泽机器人私聊"绑定"获取'}
            rules={[
              { required: true, message: '请输入邀请码' },
              { pattern: /[0-9]{6}/, message: '请输入正确邀请码' },
            ]}
          >
            <Input autoComplete={'new-password'} />
          </Form.Item>
        )}
        <Form.Item>
          <Button type={'primary'} htmlType={'submit'}>
            {isReg ? '注册' : '登录'}
          </Button>
          {isReg ? '已有账号' : '还没账号'},点击
          <a onClick={() => setReg(!isReg)}>{isReg ? '登录' : '注册'}</a>
        </Form.Item>
      </Form>
    </Modal>
  );
}

export function NavUserInfo() {
  const { info, logout } = useModel('user');
  const [loginVisible, setLoginVisible] = useState(false);
  return (
    <div>
      {info ? (
        <div>
          Hi {info.name} <a onClick={logout}>登出</a>
        </div>
      ) : (
        <Button
          ghost
          onClick={() => {
            setLoginVisible(true);
          }}
        >
          登录
        </Button>
      )}
      <LoginModel visible={loginVisible} setVisible={setLoginVisible} />
    </div>
  );
}
export function MenuUserInfo() {
  const { info, logout } = useModel('user');
  const [loginVisible, setLoginVisible] = useState(false);
  return (
    <div>
      {info ? (
        <div>
          Hi {info.name} <a onClick={logout}>登出</a>
        </div>
      ) : (
        <a
          onClick={() => {
            setLoginVisible(true);
          }}
        >
          登录
        </a>
      )}
      <LoginModel visible={loginVisible} setVisible={setLoginVisible} />
    </div>
  );
}

// src/components/NavUserInfo.vue
<template>
  <div v-if="userStore.logged">
    Hi {{ userStore.info.name }}
    <a @click="userStore.logout">登出</a>
  </div>
  <el-link v-else :underline="false" @click="userStore.showDialog=true">登录</el-link>
  <client-only>
    <el-dialog :model-value="userStore.showDialog" :before-close="close" :title="isLogin?'登录':'注册'" center>
      <el-form ref="formRef" :model="form" @submit="submit">
        <el-form-item label="用户名" prop="user" :rules="[
            { required: true, message: '请输入用户名', trigger: 'blur'},
            { pattern: /[-_a-zA-Z0-9]{6,16}/, message: '用户名需要6-16位字母数字下划线构成', trigger: 'change'},
      ]">
          <el-input v-model.trim="form.user" autocomplete="username"/>
          <span class="tip" v-if="isLogin">忘记账号?可以翻看已上传的地图，或者使用"qq+号码"代替，例"qq123456"</span>
        </el-form-item>

        <el-form-item label="密码" prop="password" :rules="[
            { required: true, message: '请输入密码', trigger: 'blur'},
            { min: 6, message: '密码需要至少6个字符', trigger: 'change'},
      ]">
          <el-input v-model="form.password" type="password"
                    :autocomplete="isLogin ? 'current-password' : 'new-password'"/>
          <span class="tip" v-if="isLogin">忘记密码?可以使用相同用户名和qq重新注册，更新密码</span>
        </el-form-item>

        <el-form-item v-if="!isLogin" label="重复密码" prop="password2" :rules="[
            { required: true, message: '请输入密码', trigger: 'blur'},
            { validator: passwordConfirmValidator, message: '重复密码不匹配,请重新输入', trigger: 'change'},
      ]">
          <el-input v-model="form.password2" type="password"/>
        </el-form-item>

        <el-form-item v-if="!isLogin" label="QQ号验证" prop="code">
          <el-input v-model="form.code" disabled>
            <template #append>
              <el-button v-if="genCodeCoolDown<=0" @click="genCode">点击获取验证码</el-button>
              <el-button v-else disabled>重新获取验证码({{ genCodeCoolDown }})</el-button>
            </template>
          </el-input>
          <el-alert v-if="form.code" type="warning" :closable="false">
            请在资源站交流群(722163668)发送消息"资源站验证 {{ form.code }}"进行验证。<br/>
            也可私聊机器人(QQ1849301538)发送消息，因为技术限制，私聊不会回复确认。<br/>
            <b>资源站会记录你的QQ号备用,继续注册即同意该条款</b>
          </el-alert>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submit">提交</el-button>
          <span v-if="isLogin">还没账号,点击<el-button link type="primary"
                                                       @click="isLogin=false">注册</el-button></span>
          <span v-else>已有账号,点击<el-button link type="primary" @click="isLogin=true">登录</el-button></span>
        </el-form-item>
      </el-form>
    </el-dialog>
  </client-only>
</template>

<script lang="ts" setup>
import {useStore} from "pinia-class-store";
import {UserStore} from "@/store/user";
import ClientOnly from "@/components/ClientOnly";
import {ElForm} from "element-plus";
import {UserApi} from "@/store/user/api";

const userStore = useStore(UserStore)
onMounted(() => {
  if (userStore.first)
    userStore.refresh()
})

function login() {
  userStore.showDialog = true
}

//model
const isLogin = ref(true)
const formRef = ref<typeof ElForm>()
const form = ref({
  user: '',
  password: '',
  password2: '',
  code: '',
})

function passwordConfirmValidator(_, v) {
  return v === form.value.password
}

const genCodeCoolDown = ref(0)

async function genCode() {
  genCodeCoolDown.value = 60
  const interval = setInterval(() => {
    genCodeCoolDown.value--
    if (genCodeCoolDown.value <= 0) clearInterval(interval)
  }, 1000)
  form.value.code = await UserApi.genCode()
}

async function submit() {
  try {
    await formRef.value!!.validate()
    if (isLogin.value)
      await userStore.login(form.value)
    else
      await userStore.register(form.value)
  } catch (e) {
  }
}

async function close() {
  userStore.showDialog = false
}
</script>

<style lang="stylus" scoped>
.tip
  display inline-block
  line-height normal
  color gray
</style>
